# Generated by Django 5.0.1 on 2024-03-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dateofbirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
